name       : haskell-hspec-core
version    : 2.4.2
release    : 1
source     :
    - http://hackage.haskell.org/package/hspec-core-2.4.2/hspec-core-2.4.2.tar.gz : 393ba143901824579b736fb4313c7e07e57eda45580e657bf24d1b1c32c0a318
license    : MIT
component  : programming.haskell
summary    : This package exposes internal types and functions that can be used to extend Hspec's functionality.
description: |
    This package exposes internal types and functions that can be used to extend Hspec's functionality.
builddeps  :
    - haskell-ansi-terminal
    - haskell-cabal-install
    - haskell-hspec-expectations
    - haskell-quickcheck-io
    - haskell-setenv
    - haskell-tf-random
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
