name       : haskell-hspec-core
version    : 2.5.1
release    : 2
source     :
    - https://hackage.haskell.org/package/hspec-core-2.5.1/hspec-core-2.5.1.tar.gz : e88e45fe851c976b4703a9c1e481c0e451abbcdcba7e40c9d26020e87b2edc79
license    : MIT
component  : programming.haskell
summary    : This package exposes internal types and functions that can be used to extend Hspec's functionality.
description: |
    This package exposes internal types and functions that can be used to extend Hspec's functionality.
builddeps  :
    - haskell-ansi-terminal
    - haskell-cabal-install
    - haskell-clock
    - haskell-hspec-expectations
    - haskell-quickcheck-io
    - haskell-setenv
    - haskell-stm
    - haskell-tf-random
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
