name       : haskell-hspec-core
version    : 2.7.1
release    : 3
source     :
    - https://hackage.haskell.org/package/hspec-core-2.7.1/hspec-core-2.7.1.tar.gz : 2ccc20f27970f753ed2e902c323f4562adaf1a31f4234b3504e02a8a50417323
license    : MIT
component  : programming.haskell
summary    : This package exposes internal types and functions that can be used to extend Hspec's functionality.
description: |
    This package exposes internal types and functions that can be used to extend Hspec's functionality.
builddeps  :
    - haskell-ansi-terminal-devel
    - haskell-cabal-install
    - haskell-clock-devel
    - haskell-hspec-expectations-devel
    - haskell-quickcheck-io-devel
    - haskell-setenv-devel
rundeps    :
    - devel:
        - haskell-ansi-terminal-devel
        - haskell-clock-devel
        - haskell-hspec-expectations-devel
        - haskell-quickcheck-io-devel
        - haskell-setenv-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
